name: build
on: [pull_request, push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get -y install libopus-dev libopusfile-dev libpulse-dev

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Build
        run: go build -mod=vendor

      - name: Run help
        run: ./webrtc-cli -h
